Use "Common Changelog" format for Changelog
nsidc/earthaccess pull request #584
Opened 2024-05-29 16:09 UTC by danielfromearth

Use [Common Changelog](https://common-changelog.org).

For instance, this change recategorizes entries into "Common Changelog" groups, formats headings, and uses an imperative mood.

2024-05-29 16:24 UTC, danielfromearth commented
@jhkennedy, @mfisher87 — following up from a mention of this yesterday — any suggestions for linting of markdown in a CI pipeline?

2024-07-05 22:36 UTC, chuckwondo requested changes

2024-07-05 22:36 UTC, chuckwondo commented on CHANGELOG.md
> +### Changed
I'm nit-picking here, but for general markdown linting, let's follow headings with a single blank line.
```suggestion
### Changed

```

2024-07-05 22:36 UTC, chuckwondo commented on CHANGELOG.md
> +- **Breaking**: [#421](https://github.com/nsidc/earthaccess/issues/421): Remove the
Place `:` inside boldface and move reference to end

2024-07-05 22:36 UTC, chuckwondo commented on CHANGELOG.md
> +    Earthdata User Acceptance Testing (UAT) system for authenticated accounts.
Move reference to ends

2024-07-05 22:36 UTC, chuckwondo commented on CHANGELOG.md
> +- distributed serialization fixed for EarthAccessFile #301 and #276
add links

2024-07-05 22:36 UTC, chuckwondo commented on CHANGELOG.md
> +- earthaccess.search_datasets() and earthaccess.search_data() can find restricted datasets #296
add link

2024-07-05 22:36 UTC, chuckwondo commented on CHANGELOG.md
> +- Fix #438 by using an authenticated session for hits()
add links

2024-07-06 01:36 UTC, danielfromearth commented
Thanks @chuckwondo for spotting these, and I will incorporate those changes!  I'm actually still working through the changelog entry-by-entry, and I'm currently about half-way through. 

Another note to address (maybe there will be more as I get to more recent entries):  I don't see the following changes listed in the changelog. Perhaps another person can double-check whether they should be added...

I think they would go in the `[0.5.3] - 2023-08-01` section:
- https://github.com/nsidc/earthaccess/pull/247
- https://github.com/nsidc/earthaccess/pull/259
- https://github.com/nsidc/earthaccess/pull/260
- https://github.com/nsidc/earthaccess/pull/261
- https://github.com/nsidc/earthaccess/pull/263
- https://github.com/nsidc/earthaccess/pull/265

2024-07-06 02:27 UTC, danielfromearth commented
Also noting these, which may be missing:

For `[0.6.0] - 2023-09-20`:
- https://github.com/nsidc/earthaccess/pull/294

For `[0.7.0] - 2023-10-31`:
- https://github.com/nsidc/earthaccess/pull/320

For `[0.8.0] - 2023-11-29`:
- https://github.com/nsidc/earthaccess/pull/340
- https://github.com/nsidc/earthaccess/pull/347

2024-07-08 17:16 UTC, danielfromearth commented
pre-commit.ci autofix

2024-07-09 15:38 UTC, danielfromearth commented
I added a couple of the missing entries mentioned above, but left out the ones that seemed like they would be uninteresting to anyone other than the developers.

I think this is ready to merge!  Was more work than I thought it would be to go through all the entries and cross-check them against the PR and issue lists on GitHub. I tried my best to capture who contributed to each PR/issue, and be as inclusive as possible, but if I missed someone, know that it wasn't intentional.  Hopefully this is much better now, and gives credit to all the effort people have been doing to keep this awesome tool going and improving.

2024-07-09 15:46 UTC, mfisher87 commented
@danielfromearth AMAZING work!!! I appreciate that this is very hard and time consuming. Also _worth it_ to show appreciation for everyone's work. I haven't had a chance to review this yet, but I'd like to make time for that in today's hack day and have a "merge party" :) Will you be there?

2024-07-09 15:50 UTC, danielfromearth commented
Thanks @mfisher87  :) 
We have some ESIP Openscapes preparation time scheduled at the same time as the first half of the hack day, but I should be there for the second half of the hack day.

2024-07-09 16:00 UTC, mfisher87 commented
Awesome. I want to spend some time on integration tests today too so I'll try and get that out of the way first ;)

2024-07-09 18:35 UTC, mfisher87 submitted a review, later dismissed

2024-07-09 18:42 UTC, mfisher87 approved these changes

2024-07-09 18:43 UTC, mfisher87 commented
Some discussion reflecting on the use of an "unreleased" section the way we do: https://github.com/vweevers/common-changelog/issues/13

2024-07-09 18:49 UTC, merged