Triaging
nsidc/earthaccess pull request #901
Opened 2024-12-15 06:54 UTC by Sherwin-14

This is the initial draft for the triaging document.

2024-12-15 18:21 UTC, mfisher87 commented
Nice work! Will look more closely this week.

Looks like there's a tradeoff to be considered here to fix linting: https://github.com/pre-commit/pre-commit-hooks#check-yaml

2024-12-16 17:49 UTC, asteiker commented
I'm wondering if some updates may be needed based on the recently closed #760 ? If it would be helpful for me to review and update accordingly, I'd be happy to help.

2024-12-16 18:43 UTC, mfisher87 commented
@asteiker that would be super helpful!!

2024-12-30 17:13 UTC, mfisher87 commented
@asteiker OK to assign this PR to you?

2025-01-12 16:11 UTC, mfisher87 requested changes
:raised_hands: Amazing work! Sorry about the number of suggestions here -- we re-organized labels in #760 to be more self-describing, and I think that helps make this document more clear!

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +[hackathon](https://github.com/nsidc/earthaccess/labels/hackathon)
Should actually look like https://github.com/nsidc/earthaccess/labels/good%20first%20issue - GitHub automatically applies the text when you paste the URL :)

```
Should actually look like https://github.com/nsidc/earthaccess/labels/good%20first%20issue
```

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +```
````suggestion
To link to a label in GitHub Markdown, copy-and-paste the URL to the label by right-clicking [any label](https://github.com/nsidc/earthaccess/labels) and selecting "Copy Link". Then, paste that label in a GitHub issue, PR, discussion, or Markdown document:

```
https://github.com/username/repository/labels/label-name
```
````

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +[hackathon](https://github.com/nsidc/earthaccess/labels/hackathon)
After our example, let's include an image that shows what it should look like when done correctly!

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +    When linking to labels, it is a good practice to use the label name as the link text, as shown in the example above. This makes it clear to others what label is being referenced, and helps to avo
```suggestion
```

This is a great tip, but if the label syntax is correct, the user shouldn't have to worry about that because GitHub handles the magic :)

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +This section will cover the guidelines for when to use the "Close Issue as Not Planned" label, and how to handle issues that are not planned or feasible.
```suggestion
This section will cover the guidelines for when to use the "Close Issue as Not Planned" feature, and how to handle issues that are not planned or feasible.
```

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +### When to Use This Label?
```suggestion
### When to "Close as not planned"?
```

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +Use the "Close Issue as Not Planned" label when:
```suggestion
Close issues as "not planned" when:
```

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +- Link to relevant documentation or resources, if applicable.
:100: Amazing callout!

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +- Feature requests and feedback.
```suggestion
- Project feedback.
```

I wanted to differentiate this from "Requesting changes or improvements" in the "What are issues?" section :)

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +### When to Migrate
```suggestion
### When to Migrate

Use your best judgement when migrating between issues and discussions. Sometimes it makes more sense to open a new issue or discussion instead of migrating, for example when there are many things being discussed, but we want to create an issue or task out of just one of those things.
```

2025-01-12 16:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +- The issue is a feature request or idea.
```suggestion
- The issue is a nebulous idea that needs to be workshopped before it can be implemented.
```

2025-01-12 16:11 UTC, mfisher87 commented
@asteiker can you also take a look?

2025-01-12 17:26 UTC, mfisher87 commented on mkdocs.yml
> +  - mermaid2
We need to install this plugin `mkdocs-mermaid2-plugin` in our docs dependencies to get the docs build working again:

https://github.com/nsidc/earthaccess/blob/91866ac18e806e2d53d6b68cd000fa372c3e010f/pyproject.toml#L90-L123

2025-01-13 15:59 UTC, mfisher87 commented
I'm not sure exactly what you mean here; are you thinking about PR reviews?

2025-01-14 18:17 UTC, mfisher87 commented
@Sherwin-14 I'd like to wait to review until the ReadTheDocs build is working again. Do you feel comfortable fixing it? Details here: https://github.com/nsidc/earthaccess/pull/901#discussion_r1912497324

2025-01-15 16:59 UTC, mfisher87 reviewed
In a rush, just leaving comments :)

2025-01-15 16:59 UTC, mfisher87 commented on mkdocs.yml
> +      - "Triaging Doc": "contributing/triaging.md"
```suggestion
      - "Maintainers Guide": "contributing/maintainers-guide.md"
      - "Triaging Guide": "contributing/triaging.md"
      - "Code of Conduct": "contributing/code-of-conduct.md"
      - "Contributing naming convention": "contributing/naming-convention.md"

```

2025-01-15 16:59 UTC, mfisher87 commented on docs/contributing/triaging.md
> +
I'd like to add back the "good first issue" label, perhaps alone in a "Special labels" section? That is one that triagers should be especially aware of!

2025-01-15 16:59 UTC, mfisher87 commented on docs/contributing/triaging.md
> +  repro == NO ==> close3[Label: 'needs reproduction' bot will auto close if no update has been made in 3 days]
>bot will auto close if no update has been made in 3 days

I think this isn't true. We have one automation for autoclosing issues, but I believe it's broken: https://github.com/nsidc/earthaccess/blob/main/.github/workflows/issue-manager.yml

We should be careful about fixing it: #895 & https://jacobtomlinson.dev/posts/2024/most-stale-bots-are-anti-user-and-anti-contributor-but-they-dont-have-to-be/

2025-01-15 16:59 UTC, mfisher87 commented on docs/contributing/triaging.md
> +  real == YES ==> real2["1. Remove 'pending triage' label 2. Add related feature label if applicable (e.g. 'feat: ssr') 3. Add priority and meta labels (see below)"]
Renders as 
![image](https://github.com/user-attachments/assets/fbddb6d1-ad79-4c7c-bf85-892ae8cf9f12)

2025-01-15 16:59 UTC, mfisher87 commented on docs/contributing/triaging.md
> +  workarounds == YES ==> p2[p2: edge case has workaround]
We don't have priority levels yet to my knowledge. @asteiker what do you think?

2025-01-15 18:25 UTC, mfisher87 commented on docs/contributing/triaging.md
> +  repro == NO ==> close3[Label: 'needs reproduction' bot will auto close if no update has been made in 3 days]
Ah, that makes sense, thanks for the context!

2025-01-16 16:13 UTC, mfisher87 commented on docs/contributing/triaging.md
> +  repro == NO ==> close3[Label: 'needs reproduction' bot will auto close if no update has been made in 3 days]
I think getting @asteiker 's eyes on this is probably the best way forward. Will you be at next week's hack day? Maybe we can work together to finalize the flowchart.

2025-01-21 18:11 UTC, mfisher87 commented on docs/contributing/triaging.md
> +- **good-first-issue**: Use this label for issues that are suitable for new contributors. These issues are designed to be approachable and not overly complex, making them an ideal starting point for
```suggestion
- **good first issue**: Use this label for issues that are suitable for new contributors. These issues are designed to be approachable and not overly complex, making them an ideal starting point for those looking to contribute to the project.
```

2025-01-30 17:41 UTC, asteiker commented on docs/contributing/triaging.md
> +  repro == NO ==> close3[Label: 'needs reproduction' bot will auto close if no update has been made in 3 days]
@mfisher87 @Sherwin-14 Apologies for my radio silence on this recently! Yes I am happy to get back into this and work together at the next hackday. I'll review this in more detail in preparation.

2025-01-30 18:07 UTC, mfisher87 commented on docs/contributing/triaging.md
> +  repro == NO ==> close3[Label: 'needs reproduction' bot will auto close if no update has been made in 3 days]
Thanks, Amy!

2025-02-18 19:23 UTC, asteiker commented
@mfisher87 I'm sharing some notes from reviewing with @Sherwin-14 during our hackday:
- It looks like there is an erroneous "Unsupported markdown: list" box but I believe Sherwin needs some guidance from you on how to remove.
- There is a step to Remove "pending triage" label, but we don't have that label to begin with. I suggest we open a new Issue to add this label to all newly entered Issues. (side note: I'd love to contribute to this if it's not too technical. If you have any guidance I'd love to hear!) I wouldn't want this to hold up the PR but otherwise that step won't make a lot of sense before we have the "pending triage" label to begin with.
- Adding thoughts on priority levels in your comment above.
- I suggest we soften the language on issues that do not follow a template (the first "no" fork). I wouldn't want this to create a perceived barrier to contributing an issue if they are basically asked to redo what they wrote originally. I believe there may be cases where either a user does not understand the difference between issue templates or feel that their issue doesn't fully belong in one or the other. Could we instead say "Identify whether an existing template is appropriate and migrate the issue to that template on behalf of the issue reporter."

2025-02-18 19:30 UTC, mfisher87 commented on docs/contributing/triaging.md
> +  workarounds == YES ==> p2[p2: edge case has workaround]
I think that sounds reasonable!

2025-02-18 19:38 UTC, mfisher87 commented
1. I have a [comment above](https://github.com/nsidc/earthaccess/pull/901#discussion_r1917026827) for this; we just need to make the thing not-numbered. I believe Sherwin and I worked on this together in a hack week and made some progress. @Sherwin-14 is there a chance you have some un-pushed work?
2. Good idea. My original advice to Sherwin was to drop this step in the flowchart to keep it simple and aim to represent how we work now. But if we think we're ready to adopt that workflow, let's do it! I think it's not too technical :) To keep with our existing patterns, how about `Needs: triage`? I suggest implementing this in the issue templates. We already have this but it doesn't work because the label name in the template doesn't match any real labels: https://github.com/nsidc/earthaccess/blob/74c0ef50b43a05fc100c2245fcaf45b472dceb0b/.github/ISSUE_TEMPLATE/bug.yml?plain=1#L7
3. Responded above :) 
4. Yes! Great call. Perhaps "request needed information from reporter and update issue on behalf of reporter"?

If we're seeing users struggling to figure out which template to use, maybe we could do more to guide them in [our config](https://github.com/nsidc/earthaccess/blob/main/.github/ISSUE_TEMPLATE/config.yml)?

2025-02-26 17:02 UTC, mfisher87 commented
@Sherwin-14 how are you feeling about the next steps for this PR?

2025-02-27 18:07 UTC, Sherwin-14 commented
> @Sherwin-14 how are you feeling about the next steps for this PR?

I was waiting for the next hackday to start working on this again. I believe collaborating on this alongside @asteiker would be the ideal path forward. We can list all the areas where improvements are needed, in that way I would also get an idea about what steps I need to take moving forward. I had individual reviews from both of you, but I feel if all of us collaborate together on this coming hackday, that would make a lot easier for us to keep a track of suggestions and improvements.

2025-03-04 15:44 UTC, asteiker commented
@Sherwin-14 Yes, let's finalize these open items together at the hackday. I would also like to start implementing the priority designation in the bug priority project view: https://github.com/orgs/nsidc/projects/10

2025-03-08 13:15 UTC, Sherwin-14 commented
> @Sherwin-14 Yes, let's finalize these open items together at the hackday. I would also like to start implementing the priority designation in the bug priority project view: https://github.com/orgs/nsidc/projects/10

Hey Amy! Could you summarize the improvements that we agreed upon on the last hackday? I do remember some of those but I guess you have a better idea about this.

2025-04-15 15:58 UTC, asteiker commented
@Sherwin-14 Here is a summary of the changes remaining:

1. Update the erroneous "Unsupported markdown: list" box. This needs to be updated to be not numbered. There may be un-pushed work on this already from a previous hackday. 

2. Update language on issues that do not follow a template (the first "no" fork). Update to: "request needed information from reporter and update issue on behalf of reporter"

Note that I also just entered https://github.com/nsidc/earthaccess/issues/984 and can work this asap so that the pending triage label removal step is applicable.

2025-05-03 11:11 UTC, Sherwin-14 commented
> @Sherwin-14 Here is a summary of the changes remaining:
> 
>     1. Update the erroneous "Unsupported markdown: list" box. This needs to be updated to be not numbered. There may be un-pushed work on this already from a previous hackday.
> 
>     2. Update language on issues that do not follow a template (the first "no" fork). Update to: "request needed information from reporter and update issue on behalf of reporter"
> 
> 
> Note that I also just entered #984 and can work this asap so that the pending triage label removal step is applicable.

Thanks @asteiker! I have a question for you on the first point. Do you want me to remove the priority labels and just preserve the tags or do you want me to remove the tags alongside priority labels.

On removing priority labels and preserving the respective tags,  the workflow diagram would look something like this.

![Screenshot From 2025-05-03 16-37-14](https://github.com/user-attachments/assets/31b58d9c-3bf8-403e-99e4-4845aac3be4b)

2025-05-25 23:32 UTC, mfisher87 commented
>Thanks @asteiker! I have a question regarding the first point. Do you want me to remove the priority labels and just preserve the tags or do you want me to remove the tags alongside priority labels.
>
> On removing priority labels and preserving the respective tags, the workflow diagram would look something like this.

Can you clarify what you mean by "tags" here? If you mean the workflow steps (rectangles) I'm all for removing them :)

2025-05-27 20:13 UTC, mfisher87 commented
:100:

I think we can remove  "Does it make earthaccess unusable" and everything underneath. Let's worry about prioritization of issues when we're ready :)

2025-06-13 20:26 UTC, mfisher87 submitted a review, later dismissed
Let's merge this once the pre-commit error is resolved. Thank you for your patience with this incredibly persistent task :sweat_smile:

2025-06-13 20:26 UTC, mfisher87 commented on mkdocs.yml
> +          format: !!python/name:mermaid2.fence_mermaid_custom
Pre-commit is complaining about this line, and I'm not sure why! Anything we can do about that?

2025-06-13 20:28 UTC, mfisher87 commented on mkdocs.yml
> +          format: !!python/name:mermaid2.fence_mermaid_custom
Looks like we can add `--unsafe` arg to pre-commit to get by: https://github.com/pre-commit/pre-commit-hooks#check-yaml

2025-06-14 11:45 UTC, Sherwin-14 commented on mkdocs.yml
> +          format: !!python/name:mermaid2.fence_mermaid_custom
> Pre-commit is complaining about this line, and I'm not sure why! Anything we can do about that?

I don't know tbh. It seems like this line is important to render the flowchart, more on this [here](https://mkdocs-mermaid2.readthedocs.io/en/latest/superfences/#usage-for-the-material-theme).

2025-06-14 14:31 UTC, mfisher87 commented on mkdocs.yml
> +          format: !!python/name:mermaid2.fence_mermaid_custom
Yeah, I don't think we should change the mkdocs config. We should change the pre-commit config! See the link above :)

2025-06-14 14:43 UTC, Sherwin-14 commented
`pre-commit` now fails because of a uv related error.

2025-06-14 16:59 UTC, mfisher87 commented
Nice, thanks for the fix! The `uv` failure has been happening for a long while, no worries! It needs a separate fix.

2025-06-14 17:13 UTC, mfisher87 commented
This PR is docs-only so ignoring the integration test failures

2025-06-14 17:13 UTC, mfisher87 approved these changes

2025-06-14 17:13 UTC, merged

2025-06-14 17:13 UTC, mfisher87 commented
Thanks, @Sherwin-14